name: rebuild-website
on:
  push:
    branches:
      - main
    paths: # only rebuild when related files change
      - "**.md"
      - "**.yml"
      - "**.json"
      - "**.tsp"  

jobs:
  rebuild-website:
    name: Trigger deploy hooks
    runs-on: ubuntu-latest
    if: github.repository == 'blue-build/modules'
    steps: 
      - run: |
          echo "website:" && \
          curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/blue-build/website/actions/workflows/deploy.yml/dispatches \
           -d '{"ref":"main"}'
      - run: sleep 3m
      - run: echo "schemas:" && curl -X POST -d {} ${{ secrets.SCHEMAS_DEPLOY_HOOK }}
      - run: sleep 3m
      - run: |
          echo "website:" && \
          curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/blue-build/website/actions/workflows/deploy.yml/dispatches \
           -d '{"ref":"main"}'
